<?php
/**
Generated BY DB2PHP By CharfiOmar
**/
class Annonce
{
    private $idAnn,$titreAnn,$prixAnn,$descriptionAnn,$dateCreAnn,$dateExpAnn,$etatAnn,$idUsr,$idCat;

    public function __construct($idAnn,$titreAnn,$prixAnn,$descriptionAnn,$dateCreAnn,$dateExpAnn,$etatAnn,$idUsr,$idCat){
    $this->idAnn = $idAnn;
    $this->titreAnn = $titreAnn;
    $this->prixAnn = $prixAnn;
    $this->descriptionAnn = $descriptionAnn;
    $this->dateCreAnn = $dateCreAnn;
    $this->dateExpAnn = $dateExpAnn;
    $this->etatAnn = $etatAnn;
    $this->idUsr = $idUsr;
    $this->idCat = $idCat;
    }

    public function add_Annonce($bdd){
        $unit = ($this->prixAnn)*0.05;
        $bdd->exec("INSERT INTO annonce(titreAnn,prixAnn,unitAnn,descriptionAnn,dateCreAnn,dateExpAnn,etatAnn,idUsr,idCat) VALUES('$this->titreAnn',$this->prixAnn,$unit,'$this->descriptionAnn',CURRENT_DATE ,'$this->dateExpAnn','$this->etatAnn',$this->idUsr,$this->idCat) ");
    }

    public function list_Annonce($bdd){
    $res = $bdd->query("SELECT * FROM annonce")->fetchAll(PDO::FETCH_OBJ);
    return $res;
    }

    public function listUsr_Annonce($bdd,$usr){
    $res = $bdd->query("SELECT * FROM annonce WHERE idUsr=$usr ")->fetchAll(PDO::FETCH_OBJ);
    return $res;
    }

    public function update_Annonce($bdd){
    $bdd->exec("UPDATE annonce SET titreAnn = '$this->titreAnn', prixAnn = '$this->prixAnn', descriptionAnn = '$this->descriptionAnn', dateCreAnn = '$this->dateCreAnn', dateExpAnn = '$this->dateExpAnn', etatAnn = '$this->etatAnn', idUsr = '$this->idUsr', idCat = '$this->idCat' WHERE idAnn ='$this->idAnn' ");
    }

    public function delete_Annonce($bdd){
    $bdd->exec("DELETE FROM annonce WHERE idAnn ='$this->idAnn'");
    }

}