<?php
/**
Generated BY DB2PHP By CharfiOmar
 **/
class Favoris
{
    private $idUsr,$idCat;

    public function __construct($idUsr,$idCat){
        $this->idUsr = $idUsr;
        $this->idCat = $idCat;
    }

    public function add_Favoris($bdd){
        $bdd->exec("INSERT INTO favoris(idCat) VALUES('$this->idCat') ");
    }

    public function list_Favoris($bdd){
        $res = $bdd->query("SELECT idCat FROM favoris WHERE idUsr ='$this->idUsr'")->fetchAll(PDO::FETCH_OBJ);
        return $res;
    }

    public function delete_Favoris($bdd){
        $bdd->exec("DELETE FROM favoris WHERE idUsr ='$this->idUsr' AND idCat ='$this->idCat'");
    }
}