<?php
/**
Generated BY DB2PHP By CharfiOmar
 **/
class Lieu
{
    private $idVille,$idAnn;

    public function __construct($idVille,$idAnn){
        $this->idVille = $idVille;
        $this->idAnn = $idAnn;
    }

    public function add_Lieu($bdd){
        $bdd->exec("INSERT INTO lieu VALUES('$this->idVille','$this->idAnn') ");
    }

    public function list_Lieu($bdd){
        $res = $bdd->query("SELECT idVille FROM lieu WHERE idAnn ='$this->idAnn'")->fetchAll(PDO::FETCH_OBJ);
        return $res;
    }

    public function delete_Lieu($bdd){
        $bdd->exec("DELETE FROM lieu WHERE idAnn ='$this->idAnn' ");
    }
}