<?php
/**
Generated BY DB2PHP By CharfiOmar
 **/
class Recherche
{
    private $idRech,$titreRech,$idCat,$idUsr,$idVille,$prixMin,$prixMax,$etat;

    public function __construct($idRech,$titreRech,$idCat,$idUsr,$idVille,$prixMin,$prixMax,$etat){
        $this->idRech = $idRech;
        $this->titreRech = $titreRech;
        $this->idCat = $idCat;
        $this->idUsr = $idUsr;
        $this->idVille = $idVille;
        $this->prixMin = $prixMin;
        $this->prixMax = $prixMax;
        $this->etat = $etat;
    }
public function add_Recherche($bdd){
    $bdd->exec("INSERT INTO recherche(titreRech,idCat,idUsr,idVille,prixMin,prixMax,etat) VALUES('$this->titreRech','$this->idCat','$this->idUsr','$this->idVille','$this->prixMin','$this->prixMax','$this->etat') ");
    }
public function list_Recherche($bdd){
    $res = $bdd->query("SELECT titreRech,idCat,idUsr,idVille,prixMin,prixMax,etat FROM recherche")->fetchAll(PDO::FETCH_OBJ);
    return $res;
    }
public function list1_Recherche($bdd){
    $res = $bdd->query("SELECT titreRech,idCat,idUsr,idVille,prixMin,prixMax,etat FROM recherche WHERE idRech ='$this->idRech' ")->fetch(PDO::FETCH_OBJ);
    return $res;
    }
public function update_Recherche($bdd){
    $bdd->exec("UPDATE recherche SET titreRech = '$this->titreRech', idCat = '$this->idCat', idUsr = '$this->idUsr', idVille = '$this->idVille', prixMin = '$this->prixMin', prixMax = '$this->prixMax', etat = '$this->etat' WHERE idRech ='$this->idRech' ");
    }
public function delete_Recherche($bdd){
    $bdd->exec("DELETE FROM recherche WHERE idRech ='$this->idRech' ");
}

}